spring.application.name=yaho

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#DB
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/yaho?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

#jwt
jwt.secret=${JWT_SECRET:change-me-in-local-env}
jwt.access-expiration-ms=1800000
jwt.refresh-expiration-ms=1209600000
